[2024-05-21T05:50:38.535+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_merging_etl_dag.extract_metacritic_data manual__2024-05-21T05:49:34.730065+00:00 [queued]>
[2024-05-21T05:50:38.543+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_merging_etl_dag.extract_metacritic_data manual__2024-05-21T05:49:34.730065+00:00 [queued]>
[2024-05-21T05:50:38.543+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-21T05:50:38.556+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): extract_metacritic_data> on 2024-05-21 05:49:34.730065+00:00
[2024-05-21T05:50:38.561+0000] {standard_task_runner.py:60} INFO - Started process 94 to run task
[2024-05-21T05:50:38.564+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_merging_etl_dag', 'extract_metacritic_data', 'manual__2024-05-21T05:49:34.730065+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_decorators.py', '--cfg-path', '/tmp/tmptaiko9ry']
[2024-05-21T05:50:38.566+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask extract_metacritic_data
[2024-05-21T05:50:38.610+0000] {task_command.py:423} INFO - Running <TaskInstance: data_merging_etl_dag.extract_metacritic_data manual__2024-05-21T05:49:34.730065+00:00 [running]> on host d75b385b4659
[2024-05-21T05:50:38.674+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_merging_etl_dag' AIRFLOW_CTX_TASK_ID='extract_metacritic_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T05:49:34.730065+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T05:49:34.730065+00:00'
[2024-05-21T05:50:38.677+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_decorators.py", line 25, in extract_metacritic_data
    return etl.extract_metacritic_data()
  File "/opt/airflow/dags/etl.py", line 19, in extract_metacritic_data
    db_url = f"postgresql+psycopg2://{config['user']}:{config['password']}@{config['host']}/{config['database']}"
TypeError: 'NoneType' object is not subscriptable
[2024-05-21T05:50:38.697+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=data_merging_etl_dag, task_id=extract_metacritic_data, execution_date=20240521T054934, start_date=20240521T055038, end_date=20240521T055038
[2024-05-21T05:50:38.706+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task extract_metacritic_data ('NoneType' object is not subscriptable; 94)
[2024-05-21T05:50:38.738+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-21T05:50:38.757+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
